version: '4'
services:
  nodered:
    build: 'Node_Red/' 
    image: custom-node-red
    container_name: nodered
    volumes: 
      - type: bind
        source: '../nodered' 
        target: /data
    restart: on-failure:10
    environment:
        - TZ=Europe/Amsterdam    
    ports:
      - "1880:1880"
    networks:
      Manubrain:
        ipv4_address: 172.16.238.2
  timeseriesdb: 
    image: influxdb:1.8
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_PASSWORD=geheim
    restart: on-failure:10
    volumes:
      - type: bind
        source: '../influxdb'
        target: /export/share/lib/influxdb
    ports:
      - "8000:8086"
    networks:
      Manubrain:
        ipv4_address: 172.16.238.3
  grafana:
    image: grafana/grafana
    volumes: 
      - type: bind
        source: '../grafana' 
        target: /export/share/lib/grafana
    ports:
      - "3000:3000"
    restart: on-failure:10
    networks:
      Manubrain:
        ipv4_address: 172.16.238.4
  chronograf:
    image: chronograf
    ports:
      - "2010:2010"
    networks:
      Manubrain:
        ipv4_address: 172.16.238.5
  jupyter:
    image: jupyter/datascience-notebook
    networks:
      Manubrain:
        ipv4_address: 172.16.238.6
    environment:
      - JUPYTER_TOKEN=easy
    volumes: 
      - type: bind
        source: '../jupyter' 
        target: /export/share/lib/jupyter
    ports:
      - "8200:8888"
    restart: on-failure:10
    command: "jupyter notebook --ip 0.0.0.0 --no-browser --allow-root"
networks:
  Manubrain:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1

